In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv('./../Data/working_data/normalised_data_6.csv')

In [54]:
df.drop(df.columns[[0]], axis = 1, inplace = True)

In [55]:
df

,District,Households surveyed,Women age 15-49 years interviewed,Men age 15-49 years interviewed,1. Population (female) age 6+ years who ever attended school (%),3. Sex ratio of the total population (females per 1000 males),4. Sex ratio at birth for children born in the last five years (females per 1000 males),8. Households using improved sanitation facility2 (%),9. Households using clean fuel for cooking3 (%),12. Women who are literate (%),...,68. Children under 5 years who are stunted11 (%),72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%),79. All women age 15-49 years who are anaemic (%),91. Cervix (%),92. Breast (%),93. Oral cavity (%),State,Region,Zone
0,Chamba,578.31,683.98,128.53,0.6751,1.13970,0.95138,0.7505,0.1999,0.7371,...,0.2937,0.1986,0.6701,0.5063,0.1884,0.0479,0.1918,HP,Rural,Northern Zone
1,Chamba,626.02,738.25,142.43,0.6884,1.12831,0.93633,0.7570,0.2538,0.7495,...,0.2990,0.1906,0.6633,0.5123,0.2032,0.0525,0.2099,HP,Total,Northern Zone
2,Kangra,1946.63,2077.83,365.15,0.8337,1.11095,0.76723,0.6675,0.3143,0.9427,...,0.2585,0.1925,0.4823,0.6142,0.2613,0.1167,0.2322,HP,Rural,Northern Zone
3,Kangra,2062.74,2149.72,398.45,0.8339,1.10672,0.78136,0.6708,0.3489,0.9433,...,0.2558,0.1876,0.4732,0.5971,0.2626,0.1145,0.2390,HP,Total,Northern Zone
4,Lahul &Spiti,35.11,29.59,8.12,0.6569,0.99365,0.78660,0.5250,0.5987,0.8091,...,0.2303,0.0964,0.9471,0.8323,0.2460,0.0931,0.3195,HP,Rural,Northern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1287,Valsad,624.17,679.94,161.39,0.7647,0.99535,1.18889,0.6122,0.5666,0.7618,...,0.4328,0.2291,0.5038,0.5086,0.2006,0.0443,0.0904,GJ,Total,Western Zone
1288,Surat,1733.85,2019.23,537.52,0.8570,0.84461,0.62906,0.8674,0.9460,0.8363,...,0.2481,0.1488,0.4030,0.3397,0.3490,0.1026,0.1408,GJ,Urban,Western Zone
1289,Surat,2195.68,2511.26,659.00,0.8285,0.88110,0.68371,0.7739,0.8340,0.8096,...,0.2997,0.1841,0.4234,0.3902,0.3565,0.1421,0.1753,GJ,Total,Western Zone
1290,Tapi,262.75,307.76,66.40,0.6256,1.06360,0.83285,0.3311,0.1605,0.6574,...,0.3635,0.4501,0.4974,0.5512,0.2356,0.0549,0.0541,GJ,Rural,Western Zone
1291,Tapi,290.78,338.97,79.34,0.6475,1.06450,0.88281,0.3859,0.2270,0.6724,...,0.3587,0.4335,0.4947,0.5435,0.2399,0.0551,0.0591,GJ,Total,Western Zone

In [56]:
df = df.drop(columns= ['District' , 'Households surveyed' , 'Women age 15-49 years interviewed' , 'Men age 15-49 years interviewed' , 'State', 'Region', 'Zone']  )

In [57]:
import statsmodels.api as sm

In [58]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [59]:
X = df.copy(deep='True')

In [60]:
X = X.drop(columns = ['68. Children under 5 years who are stunted11 (%)'])

In [61]:
Xcpy = X.copy(deep= 'True')

In [62]:
y = df['68. Children under 5 years who are stunted11 (%)']

In [63]:
y=y.values

In [64]:
X=X.values

In [65]:
y

array([0.2937, 0.299 , 0.2585, ..., 0.2997, 0.3635, 0.3587])

In [66]:
X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.637
Model:                            OLS   Adj. R-squared:                  0.630
Method:                 Least Squares   F-statistic:                     88.93
Date:                Mon, 13 Apr 2020   Prob (F-statistic):          1.50e-257
Time:                        11:38:41   Log-Likelihood:                 1796.6
No. Observations:                1292   AIC:                            -3541.
Df Residuals:                    1266   BIC:                            -3407.
Df Model:                          25
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5066      0.046     11.073      0.000       0.417       0.596
x1             0.2530      0.056      4.506      0.000       0.143       0.363
x2            -0.1119      0.031     -3.627      0.000      -0.172      -0.051
x3             0.0267      0.015      1.823      0.069      -0.002       0.055
x4            -0.0775      0.014     -5.740      0.000      -0.104      -0.051
x5            -0.0094      0.013     -0.699      0.484      -0.036       0.017
x6            -0.2632      0.055     -4.826      0.000      -0.370      -0.156
x7            -0.0034      0.033     -0.103      0.918      -0.067       0.061
x8             0.0215      0.030      0.714      0.475      -0.038       0.081
x9             0.0427      0.019      2.247      0.025       0.005       0.080
x10           -0.0817      0.016     -5.265      0.000      -0.112      -0.051
x11           -0.0389      0.014     -2.701      0.007      -0.067      -0.011
x12            0.0188      0.017      1.084      0.279      -0.015       0.053
x13           -0.0882      0.020     -4.400      0.000      -0.128      -0.049
x14           -0.0120      0.058     -0.208      0.835      -0.125       0.101
x15            0.0235      0.014      1.722      0.085      -0.003       0.050
x16            0.0011      0.014      0.075      0.941      -0.027       0.029
x17           -0.0072      0.014     -0.519      0.604      -0.034       0.020
x18            0.0212      0.062      0.342      0.733      -0.101       0.143
x19           -0.1809      0.056     -3.249      0.001      -0.290      -0.072
x20            0.2633      0.035      7.472      0.000       0.194       0.332
x21            0.1267      0.020      6.338      0.000       0.088       0.166
x22           -0.0691      0.024     -2.913      0.004      -0.116      -0.023
x23            0.0360      0.021      1.717      0.086      -0.005       0.077
x24            0.0934      0.039      2.369      0.018       0.016       0.171
x25           -0.0863      0.027     -3.190      0.001      -0.139      -0.033
==============================================================================
Omnibus:                       30.204   Durbin-Watson:                   0.831
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               32.875
Skew:                           0.341   Prob(JB):                     7.27e-08
Kurtosis:                       3.380   Cond. No.                         137.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [50]:
# variables with p-value < 0.05:

# '1. Population (female) age 6+ years who ever attended school (%)'
# '3. Sex ratio of the total population (females per 1000 males)'
#  '8. Households using improved sanitation facility2 (%)'
#  '12. Women who are literate (%)' , men - not significant
#  '15. Women age 20-24 years married before age 18 years (%)'
# '19. Any modern method (%)'
#  '30. Mothers who had at least 4 antenatal care visits (%)'
# 40. Institutional births (%)'
# '67. Total children age 6-23 months receiving an adequate diet9 10 (%)',
# '72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)'
 #'76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)',
 #      '79. All women age 15-49 years who are anaemic (%)',


### meaningless : '92. Breast (%)', '93. Oral cavity (%)'
Xcpy.columns
#x1 , x2, x4, x6, x9(?) x10, x11, x13 ,x19, x20 , x21, x22, x24 , x25

Index(['1. Population (female) age 6+ years who ever attended school (%)',
       '3. Sex ratio of the total population (females per 1000 males)',
       '4. Sex ratio at birth for children born in the last five years (females per 1000 males)',
       '8. Households using improved sanitation facility2 (%)',
       '9. Households using clean fuel for cooking3 (%)',
       '12. Women who are literate (%)', '13. Men who are literate (%)',
       '14. Women with 10 or more years of schooling (%)',
       '15. Women age 20-24 years married before age 18 years (%)',
       '19. Any modern method (%)',
       '30. Mothers who had at least 4 antenatal care visits (%)',
       '32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)',
       '40. Institutional births (%)',
       '42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)',
       '47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)',
       '53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)',
       '62. Children under age 3 years breastfed within one hour of birth8 (%)',
       '65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
       '67. Total children age 6-23 months receiving an adequate diet9 10 (%)',
       '68. Children under 5 years who are stunted11 (%)',
       '72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
       '76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)',
       '79. All women age 15-49 years who are anaemic (%)', '91. Cervix (%)',
       '92. Breast (%)', '93. Oral cavity (%)'],
      dtype='object')

In [ ]:
# Xcpy.drop(columns = [ '3. Sex ratio of the total population (females per 1000 males)',
#        '4. Sex ratio at birth for children born in the last five years (females per 1000 males)','19. Any modern method (%)', '42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)', '91. Cervix (%)',
#        '92. Breast (%)', '93. Oral cavity (%)' , '79. All women age 15-49 years who are anaemic (%)'])

In [47]:
df_new = df[['1. Population (female) age 6+ years who ever attended school (%)' , '8. Households using improved sanitation facility2 (%)',
       '9. Households using clean fuel for cooking3 (%)',  '12. Women who are literate (%)', '13. Men who are literate (%)','32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)',
       '62. Children under age 3 years breastfed within one hour of birth8 (%)',
       '65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
       '67. Total children age 6-23 months receiving an adequate diet9 10 (%)','72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
       '76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)',
       '79. All women age 15-49 years who are anaemic (%)']]

In [48]:
df_new

,1. Population (female) age 6+ years who ever attended school (%),8. Households using improved sanitation facility2 (%),9. Households using clean fuel for cooking3 (%),12. Women who are literate (%),13. Men who are literate (%),32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%),62. Children under age 3 years breastfed within one hour of birth8 (%),65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%),67. Total children age 6-23 months receiving an adequate diet9 10 (%),72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%),79. All women age 15-49 years who are anaemic (%)
0,0.6751,0.7505,0.1999,0.7371,0.9308,0.3660,0.3223,0.0611,0.0553,0.1986,0.6701,0.5063
1,0.6884,0.7570,0.2538,0.7495,0.9258,0.3892,0.3258,0.0912,0.0764,0.1906,0.6633,0.5123
2,0.8337,0.6675,0.3143,0.9427,0.9744,0.5757,0.4495,0.0849,0.1074,0.1925,0.4823,0.6142
3,0.8339,0.6708,0.3489,0.9433,0.9673,0.5782,0.4545,0.0832,0.1054,0.1876,0.4732,0.5971
4,0.6569,0.5250,0.5987,0.8091,0.9098,0.4601,0.4274,0.1155,0.0980,0.0964,0.9471,0.8323
...,...,...,...,...,...,...,...,...,...,...,...,...
1287,0.7647,0.6122,0.5666,0.7618,0.9295,0.4047,0.7044,0.0500,0.0834,0.2291,0.5038,0.5086
1288,0.8570,0.8674,0.9460,0.8363,0.9294,0.4217,0.5871,0.0001,0.0000,0.1488,0.4030,0.3397
1289,0.8285,0.7739,0.8340,0.8096,0.9247,0.3548,0.4600,0.0000,0.0000,0.1841,0.4234,0.3902
1290,0.6256,0.3311,0.1605,0.6574,0.8777,0.4537,0.3287,0.0813,0.0874,0.4501,0.4974,0.5512
1291,0.6475,0.3859,0.2270,0.6724,0.8867,0.4281,0.3589,0.0744,0.0939,0.4335,0.4947,0.5435

In [69]:
y = df['68. Children under 5 years who are stunted11 (%)'].values
X = df['3. Sex ratio of the total population (females per 1000 males)'].values

In [70]:
X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     2.586
Date:                Mon, 13 Apr 2020   Prob (F-statistic):              0.108
Time:                        11:54:57   Log-Likelihood:                 1143.0
No. Observations:                1292   AIC:                            -2282.
Df Residuals:                    1290   BIC:                            -2272.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3051      0.039      7.833      0.000       0.229       0.381
x1             0.0629      0.039      1.608      0.108      -0.014       0.140
==============================================================================
Omnibus:                       67.858   Durbin-Watson:                   0.450
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               26.816
Skew:                           0.007   Prob(JB):                     1.50e-06
Kurtosis:                       2.294   Cond. No.                         28.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.