# <font size=14> Women and Child Health: Analysis of NFHS-4 Data </font>
National Family Health Survey, 4 (2015-2016) - India

- Data for this project has been taken from https://data.gov.in/
- Link to the dataset: https://data.gov.in/catalog/key-indicators-national-family-health-survey-nfhs
<br> </br>

# <font size=11> Data Preprocessing </font>
The data is split across 30 files - one for each state of India. Each file contains district wise data for 93 attributes.

## Merging the data from the 30 files into one single file, so as to facilitate analysis on an all India level

## DATA PREPROCESSING: Feature Construction (State)

In [1]:
import os
import io
import pandas as pd
flag=0
for root, dirs, files in os.walk("./../Data/original_data"):
    for filename in files:
          name="./../Data/original_data" + "/"  +filename
          df=pd.read_csv(name)
          #print(df)
          df=df.transpose()
          df.columns = df.iloc[0]
          df=df.drop(df.index[0])
          statename=[]
          df=df.dropna(how='all')
          n=df.shape[0]

          name = filename.strip('.csv')
          for i in range(n):
            statename.append(name)

          df['State']=statename
          if(flag==0):
            dataset=df
            flag=1
          else:
            dataset=dataset.append(df)

In [2]:

print(dataset.shape)

(1549, 97)

In [3]:
dataset.to_csv('./../Data/working_data/merged_data_1.csv')

In [4]:
dataset=pd.read_csv('./../Data/working_data/merged_data_1.csv')

In [5]:
dataset=dataset.rename(columns={dataset.columns[0] : 'District' })

In [6]:
dataset

,District,Households surveyed,Women age 15-49 years interviewed,Men age 15-49 years interviewed,1. Population (female) age 6+ years who ever attended school (%),2. Population below age 15 years (%),3. Sex ratio of the total population (females per 1000 males),4. Sex ratio at birth for children born in the last five years (females per 1000 males),5. Children under age 5 years whose birth was registered (%),6. Households with electricity (%),...,85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),91. Cervix (%),92. Breast (%),93. Oral cavity (%),State
0,Srikakulam - Rural,660.0,673.0,85.0,54.3,22.2,1026.0,865.0,89.2,96.8,...,4.1,0.8,1.0,10.3,0.0,2.7,37.2,5.9,9.3,AP
1,Srikakulam - Total,784.0,815.0,104.0,58.4,22.2,1028.0,933.0,89.3,97.3,...,4.9,1.1,0.9,11.0,0.9,2.2,37.4,6.9,9.1,AP
2,Vizianagaram - Rural,635.0,689.0,75.0,51.6,23.8,1069.0,917.0,86.2,97.5,...,5.5,1.8,0.5,15.9,3.5,0.0,31.6,3.7,10.7,AP
3,Vizianagaram - Total,799.0,850.0,98.0,56.4,23.7,1066.0,864.0,88.0,98.1,...,6.4,1.7,0.4,15.9,2.7,0.0,38.0,3.8,13.7,AP
4,Visakhapatnam - Urban,373.0,396.0,57.0,74.7,21.0,1041.0,1231.0,93.0,99.4,...,8.1,2.2,1.3,8.8,2.3,1.1,15.6,3.1,11.5,AP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,South Twenty Four Parganas - Total,792.0,930.0,106.0,76.5,26.7,1037.0,1067.0,98.5,87.4,...,6.1,1.6,0.2,7.8,1.1,2.1,3.7,1.3,2.6,WB
1545,Paschim Medinipur - Rural,703.0,898.0,94.0,73.4,25.6,1062.0,868.0,96.2,95.8,...,5.0,1.2,0.5,10.4,1.1,0.0,1.6,0.5,0.7,WB
1546,Paschim Medinipur - Total,805.0,1013.0,114.0,74.7,25.2,1050.0,862.0,96.5,95.7,...,5.1,1.1,0.5,10.4,2.9,0.0,1.4,0.5,0.6,WB
1547,Purba Medinipur - Rural,716.0,826.0,113.0,77.9,24.7,997.0,1053.0,99.3,97.5,...,5.3,0.7,0.6,5.4,1.9,0.0,3.8,1.1,1.6,WB
1548,Purba Medinipur - Total,800.0,925.0,140.0,78.8,24.7,991.0,998.0,99.0,97.5,...,5.5,0.6,0.6,4.2,1.5,0.0,3.7,1.0,1.4,WB

## DATA PREPROCESSING: Feature Contruction: Region

In [7]:
region=[]
district=[]

n=dataset.shape[0]
for i in range(n):
    
    name=dataset.iloc[i]['District']
    
    if(name.find('Rural')!=-1):
        
        name=name.replace('- Rural', '')
        name=name.replace('-Rural', '')
        
        name=name.strip()
        district.append(name)
        region.append('Rural')
        
    elif(name.find('Urban')!=-1):
        name=name.replace('- Urban', '')
        name=name.replace('-Urban', '')
        name=name.strip()
        district.append(name)
        region.append('Urban')
        
    elif(name.find('Total')!=-1):
        name=name.replace('- Total', '')
        name=name.replace('-Total', '')
        name=name.strip()
        district.append(name)
        region.append('Total')
       
print(len(region))
print(len(district))
print(dataset.shape[0])

1549
1549
1549

In [8]:
dataset['Region']=region
dataset['District']=district
dataset

,District,Households surveyed,Women age 15-49 years interviewed,Men age 15-49 years interviewed,1. Population (female) age 6+ years who ever attended school (%),2. Population below age 15 years (%),3. Sex ratio of the total population (females per 1000 males),4. Sex ratio at birth for children born in the last five years (females per 1000 males),5. Children under age 5 years whose birth was registered (%),6. Households with electricity (%),...,86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),91. Cervix (%),92. Breast (%),93. Oral cavity (%),State,Region
0,Srikakulam,660.0,673.0,85.0,54.3,22.2,1026.0,865.0,89.2,96.8,...,0.8,1.0,10.3,0.0,2.7,37.2,5.9,9.3,AP,Rural
1,Srikakulam,784.0,815.0,104.0,58.4,22.2,1028.0,933.0,89.3,97.3,...,1.1,0.9,11.0,0.9,2.2,37.4,6.9,9.1,AP,Total
2,Vizianagaram,635.0,689.0,75.0,51.6,23.8,1069.0,917.0,86.2,97.5,...,1.8,0.5,15.9,3.5,0.0,31.6,3.7,10.7,AP,Rural
3,Vizianagaram,799.0,850.0,98.0,56.4,23.7,1066.0,864.0,88.0,98.1,...,1.7,0.4,15.9,2.7,0.0,38.0,3.8,13.7,AP,Total
4,Visakhapatnam,373.0,396.0,57.0,74.7,21.0,1041.0,1231.0,93.0,99.4,...,2.2,1.3,8.8,2.3,1.1,15.6,3.1,11.5,AP,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,South Twenty Four Parganas,792.0,930.0,106.0,76.5,26.7,1037.0,1067.0,98.5,87.4,...,1.6,0.2,7.8,1.1,2.1,3.7,1.3,2.6,WB,Total
1545,Paschim Medinipur,703.0,898.0,94.0,73.4,25.6,1062.0,868.0,96.2,95.8,...,1.2,0.5,10.4,1.1,0.0,1.6,0.5,0.7,WB,Rural
1546,Paschim Medinipur,805.0,1013.0,114.0,74.7,25.2,1050.0,862.0,96.5,95.7,...,1.1,0.5,10.4,2.9,0.0,1.4,0.5,0.6,WB,Total
1547,Purba Medinipur,716.0,826.0,113.0,77.9,24.7,997.0,1053.0,99.3,97.5,...,0.7,0.6,5.4,1.9,0.0,3.8,1.1,1.6,WB,Rural
1548,Purba Medinipur,800.0,925.0,140.0,78.8,24.7,991.0,998.0,99.0,97.5,...,0.6,0.6,4.2,1.5,0.0,3.7,1.0,1.4,WB,Total

## DATA PREPROCESSING: Feature Construction : Zone

In [9]:
zone={ 'Southern Zone' : ['AP', 'TN' , 'KL', 'KA', 'TG'] , 'Western Zone' : ['GA', 'MH', 'GJ'] , 'Eastern Zone' : ['OR','WB', 'BR', 'JH', 'SK'] , 'North Eastern Zone' : ['AR','NL','MN','MZ','ML','AS','TR'], 'Central Zone' : ['MP' , 'CT' , 'UP' , 'UT'], 'Northern Zone' : ['RJ', 'DL' , 'PB' , 'HR' , 'HP' , 'JK']}

In [10]:
zone_list=[]
n=dataset.shape[0]
for i in range(n):
    name=dataset.iloc[i]['State']
    for z in zone:
        if name in zone[z]:
            zone_list.append(z)
print(len(zone_list))
print(n)

1549
1549

In [11]:
dataset['Zone']=zone_list
dataset

,District,Households surveyed,Women age 15-49 years interviewed,Men age 15-49 years interviewed,1. Population (female) age 6+ years who ever attended school (%),2. Population below age 15 years (%),3. Sex ratio of the total population (females per 1000 males),4. Sex ratio at birth for children born in the last five years (females per 1000 males),5. Children under age 5 years whose birth was registered (%),6. Households with electricity (%),...,87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),91. Cervix (%),92. Breast (%),93. Oral cavity (%),State,Region,Zone
0,Srikakulam,660.0,673.0,85.0,54.3,22.2,1026.0,865.0,89.2,96.8,...,1.0,10.3,0.0,2.7,37.2,5.9,9.3,AP,Rural,Southern Zone
1,Srikakulam,784.0,815.0,104.0,58.4,22.2,1028.0,933.0,89.3,97.3,...,0.9,11.0,0.9,2.2,37.4,6.9,9.1,AP,Total,Southern Zone
2,Vizianagaram,635.0,689.0,75.0,51.6,23.8,1069.0,917.0,86.2,97.5,...,0.5,15.9,3.5,0.0,31.6,3.7,10.7,AP,Rural,Southern Zone
3,Vizianagaram,799.0,850.0,98.0,56.4,23.7,1066.0,864.0,88.0,98.1,...,0.4,15.9,2.7,0.0,38.0,3.8,13.7,AP,Total,Southern Zone
4,Visakhapatnam,373.0,396.0,57.0,74.7,21.0,1041.0,1231.0,93.0,99.4,...,1.3,8.8,2.3,1.1,15.6,3.1,11.5,AP,Urban,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,South Twenty Four Parganas,792.0,930.0,106.0,76.5,26.7,1037.0,1067.0,98.5,87.4,...,0.2,7.8,1.1,2.1,3.7,1.3,2.6,WB,Total,Eastern Zone
1545,Paschim Medinipur,703.0,898.0,94.0,73.4,25.6,1062.0,868.0,96.2,95.8,...,0.5,10.4,1.1,0.0,1.6,0.5,0.7,WB,Rural,Eastern Zone
1546,Paschim Medinipur,805.0,1013.0,114.0,74.7,25.2,1050.0,862.0,96.5,95.7,...,0.5,10.4,2.9,0.0,1.4,0.5,0.6,WB,Total,Eastern Zone
1547,Purba Medinipur,716.0,826.0,113.0,77.9,24.7,997.0,1053.0,99.3,97.5,...,0.6,5.4,1.9,0.0,3.8,1.1,1.6,WB,Rural,Eastern Zone
1548,Purba Medinipur,800.0,925.0,140.0,78.8,24.7,991.0,998.0,99.0,97.5,...,0.6,4.2,1.5,0.0,3.7,1.0,1.4,WB,Total,Eastern Zone

In [12]:
dataset.to_csv('./../Data/working_data/feature_constructed_data_2.csv', index=False)

In [13]:
dataset=pd.read_csv('./../Data/working_data/feature_constructed_data_2.csv')
dataset

,District,Households surveyed,Women age 15-49 years interviewed,Men age 15-49 years interviewed,1. Population (female) age 6+ years who ever attended school (%),2. Population below age 15 years (%),3. Sex ratio of the total population (females per 1000 males),4. Sex ratio at birth for children born in the last five years (females per 1000 males),5. Children under age 5 years whose birth was registered (%),6. Households with electricity (%),...,87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),91. Cervix (%),92. Breast (%),93. Oral cavity (%),State,Region,Zone
0,Srikakulam,660.0,673.0,85.0,54.3,22.2,1026.0,865.0,89.2,96.8,...,1.0,10.3,0.0,2.7,37.2,5.9,9.3,AP,Rural,Southern Zone
1,Srikakulam,784.0,815.0,104.0,58.4,22.2,1028.0,933.0,89.3,97.3,...,0.9,11.0,0.9,2.2,37.4,6.9,9.1,AP,Total,Southern Zone
2,Vizianagaram,635.0,689.0,75.0,51.6,23.8,1069.0,917.0,86.2,97.5,...,0.5,15.9,3.5,0.0,31.6,3.7,10.7,AP,Rural,Southern Zone
3,Vizianagaram,799.0,850.0,98.0,56.4,23.7,1066.0,864.0,88.0,98.1,...,0.4,15.9,2.7,0.0,38.0,3.8,13.7,AP,Total,Southern Zone
4,Visakhapatnam,373.0,396.0,57.0,74.7,21.0,1041.0,1231.0,93.0,99.4,...,1.3,8.8,2.3,1.1,15.6,3.1,11.5,AP,Urban,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,South Twenty Four Parganas,792.0,930.0,106.0,76.5,26.7,1037.0,1067.0,98.5,87.4,...,0.2,7.8,1.1,2.1,3.7,1.3,2.6,WB,Total,Eastern Zone
1545,Paschim Medinipur,703.0,898.0,94.0,73.4,25.6,1062.0,868.0,96.2,95.8,...,0.5,10.4,1.1,0.0,1.6,0.5,0.7,WB,Rural,Eastern Zone
1546,Paschim Medinipur,805.0,1013.0,114.0,74.7,25.2,1050.0,862.0,96.5,95.7,...,0.5,10.4,2.9,0.0,1.4,0.5,0.6,WB,Total,Eastern Zone
1547,Purba Medinipur,716.0,826.0,113.0,77.9,24.7,997.0,1053.0,99.3,97.5,...,0.6,5.4,1.9,0.0,3.8,1.1,1.6,WB,Rural,Eastern Zone
1548,Purba Medinipur,800.0,925.0,140.0,78.8,24.7,991.0,998.0,99.0,97.5,...,0.6,4.2,1.5,0.0,3.7,1.0,1.4,WB,Total,Eastern Zone

In [14]:
dataset.isna().sum().sum()

14889

## Data Cleaning : Removing rows with 'Households Surveyed' == 0

In [15]:
dataset=dataset[dataset['Households surveyed'] != 0.00]

    
dataset

,District,Households surveyed,Women age 15-49 years interviewed,Men age 15-49 years interviewed,1. Population (female) age 6+ years who ever attended school (%),2. Population below age 15 years (%),3. Sex ratio of the total population (females per 1000 males),4. Sex ratio at birth for children born in the last five years (females per 1000 males),5. Children under age 5 years whose birth was registered (%),6. Households with electricity (%),...,87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%),90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%),91. Cervix (%),92. Breast (%),93. Oral cavity (%),State,Region,Zone
0,Srikakulam,660.0,673.0,85.0,54.3,22.2,1026.0,865.0,89.2,96.8,...,1.0,10.3,0.0,2.7,37.2,5.9,9.3,AP,Rural,Southern Zone
1,Srikakulam,784.0,815.0,104.0,58.4,22.2,1028.0,933.0,89.3,97.3,...,0.9,11.0,0.9,2.2,37.4,6.9,9.1,AP,Total,Southern Zone
2,Vizianagaram,635.0,689.0,75.0,51.6,23.8,1069.0,917.0,86.2,97.5,...,0.5,15.9,3.5,0.0,31.6,3.7,10.7,AP,Rural,Southern Zone
3,Vizianagaram,799.0,850.0,98.0,56.4,23.7,1066.0,864.0,88.0,98.1,...,0.4,15.9,2.7,0.0,38.0,3.8,13.7,AP,Total,Southern Zone
4,Visakhapatnam,373.0,396.0,57.0,74.7,21.0,1041.0,1231.0,93.0,99.4,...,1.3,8.8,2.3,1.1,15.6,3.1,11.5,AP,Urban,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,South Twenty Four Parganas,792.0,930.0,106.0,76.5,26.7,1037.0,1067.0,98.5,87.4,...,0.2,7.8,1.1,2.1,3.7,1.3,2.6,WB,Total,Eastern Zone
1545,Paschim Medinipur,703.0,898.0,94.0,73.4,25.6,1062.0,868.0,96.2,95.8,...,0.5,10.4,1.1,0.0,1.6,0.5,0.7,WB,Rural,Eastern Zone
1546,Paschim Medinipur,805.0,1013.0,114.0,74.7,25.2,1050.0,862.0,96.5,95.7,...,0.5,10.4,2.9,0.0,1.4,0.5,0.6,WB,Total,Eastern Zone
1547,Purba Medinipur,716.0,826.0,113.0,77.9,24.7,997.0,1053.0,99.3,97.5,...,0.6,5.4,1.9,0.0,3.8,1.1,1.6,WB,Rural,Eastern Zone
1548,Purba Medinipur,800.0,925.0,140.0,78.8,24.7,991.0,998.0,99.0,97.5,...,0.6,4.2,1.5,0.0,3.7,1.0,1.4,WB,Total,Eastern Zone

In [16]:
dataset.isna().sum()

District                                                             0
Households surveyed                                                 14
Women age 15-49 years interviewed                                   13
Men age 15-49 years interviewed                                     13
1. Population (female) age 6+ years who ever attended school (%)     0
                                                                    ..
92. Breast (%)                                                       1
93. Oral cavity (%)                                                  1
State                                                                0
Region                                                               0
Zone                                                                 0
Length: 100, dtype: int64

In [17]:
dataset.isna().sum().sum()

14052

## Dividing attributes into categories

In [18]:
attribute_categories={'population' : [] , 'literacy' : [] , 'marriage': [] , 'family_planning' : [] , 'maternity_care' : [] , 'delivery_care': [], 'child_immunisation' : [] , 'childhood_diseases' : [] , 'child_nutrition':[], 'adult_nutrition':[], 'anaemia': [], 'blood_sugar_level' : [], 'hypertension': [] , 'women_examination' : []    }

In [19]:
for i in range(len(dataset.columns)):
                if(i<=14):
                   attribute_categories['population'].append(dataset.columns[i])
                elif(i<=17):
                    attribute_categories['literacy'].append(dataset.columns[i])
                elif(i<=20):
                    attribute_categories['marriage'].append(dataset.columns[i])
                elif(i<=31):
                    attribute_categories['family_planning'].append(dataset.columns[i])
                elif(i<=42):
                    attribute_categories['maternity_care'].append(dataset.columns[i])
                elif(i<=49):
                    attribute_categories['delivery_care'].append(dataset.columns[i])
                elif(i<=58):
                    attribute_categories['child_immunisation'].append(dataset.columns[i])
                elif(i<=64):
                    attribute_categories['childhood_diseases'].append(dataset.columns[i])
                elif(i<=74):
                    attribute_categories['child_nutrition'].append(dataset.columns[i])
                elif(i<=78):
                    attribute_categories['adult_nutrition'].append(dataset.columns[i])
                elif(i<=83):
                    attribute_categories['anaemia'].append(dataset.columns[i])
                elif(i<=87):
                    attribute_categories['blood_sugar_level'].append(dataset.columns[i])
                elif(i<=90):
                    attribute_categories['hypertension'].append(dataset.columns[i])
                elif(i<=93):
                    attribute_categories['hypertension'].append(dataset.columns[i])
                elif(i<=96):
                    attribute_categories['women_examination'].append(dataset.columns[i])
                else:
                    attribute_categories['population'].append(dataset.columns[i])

In [20]:
attribute_categories

{'population': ['District',
  'Households surveyed',
  'Women age 15-49 years interviewed',
  'Men age 15-49 years interviewed',
  '1. Population (female) age 6+ years who ever attended school (%)',
  '2. Population below age 15 years (%)',
  '3. Sex ratio of the total population (females per 1000 males)',
  '4. Sex ratio at birth for children born in the last five years (females per 1000 males)',
  '5. Children under age 5 years whose birth was registered (%)',
  '6. Households with electricity (%)',
  '7. Households with an improved drinking-water source1 (%)',
  '8. Households using improved sanitation facility2 (%)',
  '9. Households using clean fuel for cooking3 (%)',
  '10. Households using iodized salt (%)',
  '11. Households with any usual member covered by a health scheme or health insurance (%)',
  'State',
  'Region',
  'Zone'],
 'literacy': ['12. Women who are literate (%)',
  '13. Men who are literate (%)',
  '14. Women with 10 or more years of schooling (%)'],
 'marriage': ['15. Women age 20-24 years married before age 18 years (%)',
  '16. Men age 25-29 years married before age 21 years (%)',
  '17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)'],
 'family_planning': ['18. Any method (%)',
  '19. Any modern method (%)',
  '20. Female sterilization (%)',
  '21. Male sterilization (%)',
  '22. IUD/PPIUD (%)',
  '23. Pill (%)',
  '24. Condom (%)',
  '25. Total unmet need (%)',
  '26. Unmet need for spacing (%)',
  '27. Health worker ever talked to female non-users about family planning5 (%)',
  '28. Current users ever told about side effects of current method (%)'],
 'maternity_care': ['29. Mothers who had antenatal check-up in the first trimester (%)',
  '30. Mothers who had at least 4 antenatal care visits (%)',
  '31. Mothers whose last birth was protected against neonatal tetanus6 (%)',
  '32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)',
  '33. Mothers who had full antenatal care7 (%)',
  '34. Registered pregnancies for which the mother received Mother and Child Protection (MCP) card (%)',
  '35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
  '36. Mothers who received financial assistance under Janani Suraksha Yojana (JSY) for births delivered in an institution (%)',
  '37. Average out of pocket expenditure per delivery in public health facility (Rs.)',
  '38. Children born at home who were taken to a health facility for check-up within 24 hours of birth (%)',
  '39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)'],
 'delivery_care': ['40. Institutional births (%)',
  '41. Institutional births in public facility (%)',
  '42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)',
  '43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)',
  '44. Births delivered by caesarean section (%)',
  '45. Births in a private health facility delivered by caesarean section (%)',
  '46. Births in a public health facility delivered by caesarean section (%)'],
 'child_immunisation': ['47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)',
  '48. Children age 12-23 months who have received BCG (%)',
  '49. Children age 12-23 months who have received 3 doses of polio vaccine (%)',
  '50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)',
  '51. Children age 12-23 months who have received measles vaccine (%)',
  '52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)',
  '53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)',
  '54. Children age 12-23 months who received most of the vaccinations in public health facility (%)',
  '55. Children age 12-23 months who received most of the vaccinations in private health facility (%)'],
 'childhood_diseases': ['56. Prevalence of diarrhoea (reported) in the last 2 weeks preceding the survey (%)',
  '57. Children with diarrhoea in the last 2 weeks who received oral rehydration salts (ORS) (%)',
  '58. Children with diarrhoea in the last 2 weeks who received zinc (%)',
  '59. Children with diarrhoea in the last 2 weeks taken to a health facility (%)',
  '60. Prevalence of symptoms of acute respiratory infection (ARI) in the last 2 weeks preceding the survey (%)',
  '61. Children with fever or symptoms of ARI in the last 2 weeks preceding the survey taken to a health facility (%)'],
 'child_nutrition': ['62. Children under age 3 years breastfed within one hour of birth8 (%)',
  '63. Children under age 6 months exclusively breastfed9 (%)',
  '64. Children age 6-8 months receiving solid or semi-solid food and breastmilk9 (%)',
  '65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
  '66. Non-breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
  '67. Total children age 6-23 months receiving an adequate diet9 10 (%)',
  '68. Children under 5 years who are stunted11 (%)',
  '69. Children under 5 years who are wasted11 (%)',
  '70. Children under 5 years who are severely wasted12 (%)',
  '71. Children under 5 years who are underweight11 (%)'],
 'adult_nutrition': ['72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
  '73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
  '74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)',
  '75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)'],
 'anaemia': ['76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)',
  '77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)',
  '78. Pregnant women age 15-49 years who are anaemic (<11.0 g/dl) (%)',
  '79. All women age 15-49 years who are anaemic (%)',
  '80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)'],
 'blood_sugar_level': ['81. Blood sugar level - high (>140 mg/dl) (%)',
  '82. Blood sugar level - very high (>160 mg/dl) (%)',
  '83. Blood sugar level - high (>140 mg/dl) (%)',
  '84. Blood sugar level - very high (>160 mg/dl) (%)'],
 'hypertension': ['85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
  '86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
  '87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)',
  '88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
  '89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
  '90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)'],
 'women_examination': ['91. Cervix (%)',
  '92. Breast (%)',
  '93. Oral cavity (%)']}

In [21]:
dataset_2=dataset[dataset['Region'] != 'Total']

    
print(dataset_2.isna().sum())
print(dataset_2.shape)

District                                                             0
Households surveyed                                                 14
Women age 15-49 years interviewed                                   13
Men age 15-49 years interviewed                                     13
1. Population (female) age 6+ years who ever attended school (%)     0
                                                                    ..
92. Breast (%)                                                       1
93. Oral cavity (%)                                                  1
State                                                                0
Region                                                               0
Zone                                                                 0
Length: 100, dtype: int64
(913, 100)

In [22]:
dataset_2.isna().sum().sum()

11028

## Data Cleaning : Removing attributes with many missing (NA) values

In [23]:
pd.set_option('display.max_rows', 500)
num_of_na=list(dataset_2.isna().sum())
columns_to_drop=[]
for i in range(len(num_of_na)):
    if num_of_na[i] >= 0.3*dataset_2.shape[0]:
        
        
        columns_to_drop.append(dataset_2.columns[i])

print(columns_to_drop)
dataset2=dataset_2.drop(columns_to_drop,axis=1)
print(dataset2.shape[1])
print(dataset_2.shape[1])

['16. Men age 25-29 years married before age 21 years (%)', '38. Children born at home who were taken to a health facility for check-up within 24 hours of birth (%)', '45. Births in a private health facility delivered by caesarean section (%)', '57. Children with diarrhoea in the last 2 weeks who received oral rehydration salts (ORS) (%)', '58. Children with diarrhoea in the last 2 weeks who received zinc (%)', '59. Children with diarrhoea in the last 2 weeks taken to a health facility (%)', '61. Children with fever or symptoms of ARI in the last 2 weeks preceding the survey taken to a health facility (%)', '63. Children under age 6 months exclusively breastfed9 (%)', '64. Children age 6-8 months receiving solid or semi-solid food and breastmilk9 (%)', '66. Non-breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)', '78. Pregnant women age 15-49 years who are anaemic (<11.0 g/dl) (%)']
89
100

In [24]:
dataset2.isna().sum().sum()

4576

In [25]:
dataset2.columns

Index(['District', 'Households surveyed', 'Women age 15-49 years interviewed',
       'Men age 15-49 years interviewed',
       '1. Population (female) age 6+ years who ever attended school (%)',
       '2. Population below age 15 years (%)',
       '3. Sex ratio of the total population (females per 1000 males)',
       '4. Sex ratio at birth for children born in the last five years (females per 1000 males)',
       '5. Children under age 5 years whose birth was registered (%)',
       '6. Households with electricity (%)',
       '7. Households with an improved drinking-water source1 (%)',
       '8. Households using improved sanitation facility2 (%)',
       '9. Households using clean fuel for cooking3 (%)',
       '10. Households using iodized salt (%)',
       '11. Households with any usual member covered by a health scheme or health insurance (%)',
       '12. Women who are literate (%)', '13. Men who are literate (%)',
       '14. Women with 10 or more years of schooling (%)',
       '15. Women age 20-24 years married before age 18 years (%)',
       '17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)',
       '18. Any method (%)', '19. Any modern method (%)',
       '20. Female sterilization (%)', '21. Male sterilization (%)',
       '22. IUD/PPIUD (%)', '23. Pill (%)', '24. Condom (%)',
       '25. Total unmet need (%)', '26. Unmet need for spacing (%)',
       '27. Health worker ever talked to female non-users about family planning5 (%)',
       '28. Current users ever told about side effects of current method (%)',
       '29. Mothers who had antenatal check-up in the first trimester (%)',
       '30. Mothers who had at least 4 antenatal care visits (%)',
       '31. Mothers whose last birth was protected against neonatal tetanus6 (%)',
       '32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)',
       '33. Mothers who had full antenatal care7 (%)',
       '34. Registered pregnancies for which the mother received Mother and Child Protection (MCP) card (%)',
       '35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
       '36. Mothers who received financial assistance under Janani Suraksha Yojana (JSY) for births delivered in an institution (%)',
       '37. Average out of pocket expenditure per delivery in public health facility (Rs.)',
       '39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
       '40. Institutional births (%)',
       '41. Institutional births in public facility (%)',
       '42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)',
       '43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)',
       '44. Births delivered by caesarean section (%)',
       '46. Births in a public health facility delivered by caesarean section (%)',
       '47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)',
       '48. Children age 12-23 months who have received BCG (%)',
       '49. Children age 12-23 months who have received 3 doses of polio vaccine (%)',
       '50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)',
       '51. Children age 12-23 months who have received measles vaccine (%)',
       '52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)',
       '53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)',
       '54. Children age 12-23 months who received most of the vaccinations in public health facility (%)',
       '55. Children age 12-23 months who received most of the vaccinations in private health facility (%)',
       '56. Prevalence of diarrhoea (reported) in the last 2 weeks preceding the survey (%)',
       '60. Prevalence of symptoms of acute respiratory infection (ARI) in the last 2 weeks preceding the survey (%)',
       '62. Children under age 3 years breastfed within one hour of birth8 (%)',
       '65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
       '67. Total children age 6-23 months receiving an adequate diet9 10 (%)',
       '68. Children under 5 years who are stunted11 (%)',
       '69. Children under 5 years who are wasted11 (%)',
       '70. Children under 5 years who are severely wasted12 (%)',
       '71. Children under 5 years who are underweight11 (%)',
       '72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
       '73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
       '74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)',
       '75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)',
       '76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)',
       '77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)',
       '79. All women age 15-49 years who are anaemic (%)',
       '80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)',
       '81. Blood sugar level - high (>140 mg/dl) (%)',
       '82. Blood sugar level - very high (>160 mg/dl) (%)',
       '83. Blood sugar level - high (>140 mg/dl) (%)',
       '84. Blood sugar level - very high (>160 mg/dl) (%)',
       '85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
       '86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
       '87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)',
       '88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
       '89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
       '90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)',
       '91. Cervix (%)', '92. Breast (%)', '93. Oral cavity (%)', 'State',
       'Region', 'Zone'],
      dtype='object')

In [26]:
len(dataset2.columns)

89

In [27]:
dataset2.corr()['68. Children under 5 years who are stunted11 (%)']

Households surveyed                                                                                                                  0.156765
Women age 15-49 years interviewed                                                                                                    0.194477
Men age 15-49 years interviewed                                                                                                      0.073544
1. Population (female) age 6+ years who ever attended school (%)                                                                    -0.577464
2. Population below age 15 years (%)                                                                                                 0.677540
3. Sex ratio of the total population (females per 1000 males)                                                                        0.008757
4. Sex ratio at birth for children born in the last five years (females per 1000 males)                                             -0.029723
5. Children under age 5 years whose birth was registered (%)                                                                        -0.485172
6. Households with electricity (%)                                                                                                  -0.586164
7. Households with an improved drinking-water source1 (%)                                                                            0.005558
8. Households using improved sanitation facility2 (%)                                                                               -0.607010
9. Households using clean fuel for cooking3 (%)                                                                                     -0.520680
10. Households using iodized salt (%)                                                                                               -0.112023
11. Households with any usual member covered by a health scheme or health insurance (%)                                             -0.291284
12. Women who are literate (%)                                                                                                      -0.650422
13. Men who are literate (%)                                                                                                        -0.514971
14. Women with 10 or more years of schooling (%)                                                                                    -0.591046
15. Women age 20-24 years married before age 18 years (%)                                                                            0.538721
17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)                                         0.268249
18. Any method (%)                                                                                                                  -0.242526
19. Any modern method (%)                                                                                                           -0.269643
20. Female sterilization (%)                                                                                                        -0.110683
21. Male sterilization (%)                                                                                                          -0.101187
22. IUD/PPIUD (%)                                                                                                                   -0.272373
23. Pill (%)                                                                                                                        -0.124883
24. Condom (%)                                                                                                                      -0.127591
25. Total unmet need (%)                                                                                                             0.214041
26. Unmet need for spacing (%)                                                                                                       0.142893
27. Health worker ever talked to female non-users about family planning5 (%)                                                        -0.081365
28. Current users ever told about side effects of current method (%)                                                                -0.207077
29. Mothers who had antenatal check-up in the first trimester (%)                                                                   -0.488159
30. Mothers who had at least 4 antenatal care visits (%)                                                                            -0.572111
31. Mothers whose last birth was protected against neonatal tetanus6 (%)                                                            -0.029673
32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)                                           -0.490050
33. Mothers who had full antenatal care7 (%)                                                                                        -0.507273
34. Registered pregnancies for which the mother received Mother and Child Protection (MCP) card (%)                                 -0.139611
35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)    -0.457386
36. Mothers who received financial assistance under Janani Suraksha Yojana (JSY) for births delivered in an institution (%)          0.366885
37. Average out of pocket expenditure per delivery in public health facility (Rs.)                                                  -0.266661
39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)   -0.223621
40. Institutional births (%)                                                                                                        -0.455087
41. Institutional births in public facility (%)                                                                                     -0.097300
42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)                                                0.264234
43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)                                                            -0.463439
44. Births delivered by caesarean section (%)                                                                                       -0.598222
46. Births in a public health facility delivered by caesarean section (%)                                                           -0.606337
47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)                                       -0.290314
48. Children age 12-23 months who have received BCG (%)                                                                             -0.111012
49. Children age 12-23 months who have received 3 doses of polio vaccine (%)                                                        -0.269135
50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)                                                          -0.250695
51. Children age 12-23 months who have received measles vaccine (%)                                                                 -0.204716
52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)                                                  -0.284542
53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)                                                     -0.299153
54. Children age 12-23 months who received most of the vaccinations in public health facility (%)                                    0.095430
55. Children age 12-23 months who received most of the vaccinations in private health facility (%)                                  -0.307889
56. Prevalence of diarrhoea (reported) in the last 2 weeks preceding the survey (%)                                                  0.198947
60. Prevalence of symptoms of acute respiratory infection (ARI) in the last 2 weeks preceding the survey (%)                         0.024156
62. Children under age 3 years breastfed within one hour of birth8 (%)                                                              -0.277880
65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)                                                       -0.369382
67. Total children age 6-23 months receiving an adequate diet9 10 (%)                                                               -0.412613
68. Children under 5 years who are stunted11 (%)                                                                                     1.000000
69. Children under 5 years who are wasted11 (%)                                                                                      0.247307
70. Children under 5 years who are severely wasted12 (%)                                                                             0.120229
71. Children under 5 years who are underweight11 (%)                                                                                 0.767173
72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                                                          0.633503
73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                                                            0.552667
74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)                                                                        -0.636356
75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)                                                                          -0.573015
76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)                                                                        0.383067
77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)                                                              0.276866
79. All women age 15-49 years who are anaemic (%)                                                                                    0.282893
80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)                                                                             0.328163
81. Blood sugar level - high (>140 mg/dl) (%)                                                                                       -0.382776
82. Blood sugar level - very high (>160 mg/dl) (%)                                                                                  -0.405969
83. Blood sugar level - high (>140 mg/dl) (%)                                                                                       -0.188734
84. Blood sugar level - very high (>160 mg/dl) (%)                                                                                  -0.221248
85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)                                           -0.316447
86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)                                               -0.286862
87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)                                                           -0.150381
88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)                                           -0.273260
89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)                                               -0.231085
90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)                                                           -0.167482
91. Cervix (%)                                                                                                                      -0.328280
92. Breast (%)                                                                                                                      -0.321384
93. Oral cavity (%)                                                                                                                 -0.489341
Name: 68. Children under 5 years who are stunted11 (%), dtype: float64

## DATA PREPROCESSING :  Feature Subset Selection <br/> ( Based on domain knowledge and correlation between different attributes)

### Attribute Subset Selection (Irrelevant Features)

In [28]:
dataset3=dataset2.drop(['Households surveyed',
                        'Women age 15-49 years interviewed',
       'Men age 15-49 years interviewed',
       '2. Population below age 15 years (%)',
       '5. Children under age 5 years whose birth was registered (%)',
        '27. Health worker ever talked to female non-users about family planning5 (%)',
        '28. Current users ever told about side effects of current method (%)',
        '34. Registered pregnancies for which the mother received Mother and Child Protection (MCP) card (%)',
        '36. Mothers who received financial assistance under Janani Suraksha Yojana (JSY) for births delivered in an institution (%)',
                      '37. Average out of pocket expenditure per delivery in public health facility (Rs.)',
                        '56. Prevalence of diarrhoea (reported) in the last 2 weeks preceding the survey (%)',
                        '60. Prevalence of symptoms of acute respiratory infection (ARI) in the last 2 weeks preceding the survey (%)',
       '81. Blood sugar level - high (>140 mg/dl) (%)',
       '82. Blood sugar level - very high (>160 mg/dl) (%)',
       '83. Blood sugar level - high (>140 mg/dl) (%)',
       '84. Blood sugar level - very high (>160 mg/dl) (%)',
       '85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
       '86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
       '87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)',
       '88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
       '89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
       '90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)',
       '91. Cervix (%)', 
       '92. Breast (%)', 
       '93. Oral cavity (%)',
                       ], axis=1)

In [29]:
len(dataset3.columns)

64

In [30]:
dataset3.isna().sum().sum()

3635

### Correlation Matrix

In [31]:
attribute_categories

{'population': ['District',
  'Households surveyed',
  'Women age 15-49 years interviewed',
  'Men age 15-49 years interviewed',
  '1. Population (female) age 6+ years who ever attended school (%)',
  '2. Population below age 15 years (%)',
  '3. Sex ratio of the total population (females per 1000 males)',
  '4. Sex ratio at birth for children born in the last five years (females per 1000 males)',
  '5. Children under age 5 years whose birth was registered (%)',
  '6. Households with electricity (%)',
  '7. Households with an improved drinking-water source1 (%)',
  '8. Households using improved sanitation facility2 (%)',
  '9. Households using clean fuel for cooking3 (%)',
  '10. Households using iodized salt (%)',
  '11. Households with any usual member covered by a health scheme or health insurance (%)',
  'State',
  'Region',
  'Zone'],
 'literacy': ['12. Women who are literate (%)',
  '13. Men who are literate (%)',
  '14. Women with 10 or more years of schooling (%)'],
 'marriage': ['15. Women age 20-24 years married before age 18 years (%)',
  '16. Men age 25-29 years married before age 21 years (%)',
  '17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)'],
 'family_planning': ['18. Any method (%)',
  '19. Any modern method (%)',
  '20. Female sterilization (%)',
  '21. Male sterilization (%)',
  '22. IUD/PPIUD (%)',
  '23. Pill (%)',
  '24. Condom (%)',
  '25. Total unmet need (%)',
  '26. Unmet need for spacing (%)',
  '27. Health worker ever talked to female non-users about family planning5 (%)',
  '28. Current users ever told about side effects of current method (%)'],
 'maternity_care': ['29. Mothers who had antenatal check-up in the first trimester (%)',
  '30. Mothers who had at least 4 antenatal care visits (%)',
  '31. Mothers whose last birth was protected against neonatal tetanus6 (%)',
  '32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)',
  '33. Mothers who had full antenatal care7 (%)',
  '34. Registered pregnancies for which the mother received Mother and Child Protection (MCP) card (%)',
  '35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
  '36. Mothers who received financial assistance under Janani Suraksha Yojana (JSY) for births delivered in an institution (%)',
  '37. Average out of pocket expenditure per delivery in public health facility (Rs.)',
  '38. Children born at home who were taken to a health facility for check-up within 24 hours of birth (%)',
  '39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)'],
 'delivery_care': ['40. Institutional births (%)',
  '41. Institutional births in public facility (%)',
  '42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)',
  '43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)',
  '44. Births delivered by caesarean section (%)',
  '45. Births in a private health facility delivered by caesarean section (%)',
  '46. Births in a public health facility delivered by caesarean section (%)'],
 'child_immunisation': ['47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)',
  '48. Children age 12-23 months who have received BCG (%)',
  '49. Children age 12-23 months who have received 3 doses of polio vaccine (%)',
  '50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)',
  '51. Children age 12-23 months who have received measles vaccine (%)',
  '52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)',
  '53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)',
  '54. Children age 12-23 months who received most of the vaccinations in public health facility (%)',
  '55. Children age 12-23 months who received most of the vaccinations in private health facility (%)'],
 'childhood_diseases': ['56. Prevalence of diarrhoea (reported) in the last 2 weeks preceding the survey (%)',
  '57. Children with diarrhoea in the last 2 weeks who received oral rehydration salts (ORS) (%)',
  '58. Children with diarrhoea in the last 2 weeks who received zinc (%)',
  '59. Children with diarrhoea in the last 2 weeks taken to a health facility (%)',
  '60. Prevalence of symptoms of acute respiratory infection (ARI) in the last 2 weeks preceding the survey (%)',
  '61. Children with fever or symptoms of ARI in the last 2 weeks preceding the survey taken to a health facility (%)'],
 'child_nutrition': ['62. Children under age 3 years breastfed within one hour of birth8 (%)',
  '63. Children under age 6 months exclusively breastfed9 (%)',
  '64. Children age 6-8 months receiving solid or semi-solid food and breastmilk9 (%)',
  '65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
  '66. Non-breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)',
  '67. Total children age 6-23 months receiving an adequate diet9 10 (%)',
  '68. Children under 5 years who are stunted11 (%)',
  '69. Children under 5 years who are wasted11 (%)',
  '70. Children under 5 years who are severely wasted12 (%)',
  '71. Children under 5 years who are underweight11 (%)'],
 'adult_nutrition': ['72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
  '73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)',
  '74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)',
  '75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)'],
 'anaemia': ['76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)',
  '77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)',
  '78. Pregnant women age 15-49 years who are anaemic (<11.0 g/dl) (%)',
  '79. All women age 15-49 years who are anaemic (%)',
  '80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)'],
 'blood_sugar_level': ['81. Blood sugar level - high (>140 mg/dl) (%)',
  '82. Blood sugar level - very high (>160 mg/dl) (%)',
  '83. Blood sugar level - high (>140 mg/dl) (%)',
  '84. Blood sugar level - very high (>160 mg/dl) (%)'],
 'hypertension': ['85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
  '86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
  '87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)',
  '88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
  '89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)',
  '90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)'],
 'women_examination': ['91. Cervix (%)',
  '92. Breast (%)',
  '93. Oral cavity (%)']}

In [32]:
dataset2.isna().sum()

District                                                                                                                               0
Households surveyed                                                                                                                   14
Women age 15-49 years interviewed                                                                                                     13
Men age 15-49 years interviewed                                                                                                       13
1. Population (female) age 6+ years who ever attended school (%)                                                                       0
2. Population below age 15 years (%)                                                                                                   0
3. Sex ratio of the total population (females per 1000 males)                                                                          0
4. Sex ratio at birth for children born in the last five years (females per 1000 males)                                               77
5. Children under age 5 years whose birth was registered (%)                                                                          27
6. Households with electricity (%)                                                                                                     1
7. Households with an improved drinking-water source1 (%)                                                                              1
8. Households using improved sanitation facility2 (%)                                                                                  1
9. Households using clean fuel for cooking3 (%)                                                                                        1
10. Households using iodized salt (%)                                                                                                  1
11. Households with any usual member covered by a health scheme or health insurance (%)                                                1
12. Women who are literate (%)                                                                                                         1
13. Men who are literate (%)                                                                                                          65
14. Women with 10 or more years of schooling (%)                                                                                       1
15. Women age 20-24 years married before age 18 years (%)                                                                             63
17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)                                          67
18. Any method (%)                                                                                                                     4
19. Any modern method (%)                                                                                                              4
20. Female sterilization (%)                                                                                                           4
21. Male sterilization (%)                                                                                                             4
22. IUD/PPIUD (%)                                                                                                                      4
23. Pill (%)                                                                                                                           4
24. Condom (%)                                                                                                                         4
25. Total unmet need (%)                                                                                                               4
26. Unmet need for spacing (%)                                                                                                         4
27. Health worker ever talked to female non-users about family planning5 (%)                                                           8
28. Current users ever told about side effects of current method (%)                                                                 174
29. Mothers who had antenatal check-up in the first trimester (%)                                                                     39
30. Mothers who had at least 4 antenatal care visits (%)                                                                              39
31. Mothers whose last birth was protected against neonatal tetanus6 (%)                                                              39
32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)                                             39
33. Mothers who had full antenatal care7 (%)                                                                                          39
34. Registered pregnancies for which the mother received Mother and Child Protection (MCP) card (%)                                   65
35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)      39
36. Mothers who received financial assistance under Janani Suraksha Yojana (JSY) for births delivered in an institution (%)           59
37. Average out of pocket expenditure per delivery in public health facility (Rs.)                                                   143
39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)     39
40. Institutional births (%)                                                                                                          28
41. Institutional births in public facility (%)                                                                                       28
42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)                                                 28
43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)                                                              28
44. Births delivered by caesarean section (%)                                                                                         28
46. Births in a public health facility delivered by caesarean section (%)                                                             85
47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)                                        242
48. Children age 12-23 months who have received BCG (%)                                                                              242
49. Children age 12-23 months who have received 3 doses of polio vaccine (%)                                                         242
50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)                                                           242
51. Children age 12-23 months who have received measles vaccine (%)                                                                  242
52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)                                                   242
53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)                                                       41
54. Children age 12-23 months who received most of the vaccinations in public health facility (%)                                    254
55. Children age 12-23 months who received most of the vaccinations in private health facility (%)                                   254
56. Prevalence of diarrhoea (reported) in the last 2 weeks preceding the survey (%)                                                   31
60. Prevalence of symptoms of acute respiratory infection (ARI) in the last 2 weeks preceding the survey (%)                          31
62. Children under age 3 years breastfed within one hour of birth8 (%)                                                                70
65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)                                                        209
67. Total children age 6-23 months receiving an adequate diet9 10 (%)                                                                136
68. Children under 5 years who are stunted11 (%)                                                                                      37
69. Children under 5 years who are wasted11 (%)                                                                                       37
70. Children under 5 years who are severely wasted12 (%)                                                                              37
71. Children under 5 years who are underweight11 (%)                                                                                  37
72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                                                            2
73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                                                             69
74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)                                                                           2
75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)                                                                            69
76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)                                                                         41
77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)                                                                2
79. All women age 15-49 years who are anaemic (%)                                                                                      2
80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)                                                                              70
81. Blood sugar level - high (>140 mg/dl) (%)                                                                                          2
82. Blood sugar level - very high (>160 mg/dl) (%)                                                                                     2
83. Blood sugar level - high (>140 mg/dl) (%)                                                                                         70
84. Blood sugar level - very high (>160 mg/dl) (%)                                                                                    70
85. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)                                              3
86. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)                                                  3
87. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)                                                              3
88. Slightly above normal (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)                                             69
89. Moderately high (Systolic 160-179 mm of Hg and/or Diastolic 100-109 mm of Hg) (%)                                                 69
90. Very high (Systolic ?180 mm of Hg and/or Diastolic ?110 mm of Hg) (%)                                                             69
91. Cervix (%)                                                                                                                         1
92. Breast (%)                                                                                                                         1
93. Oral cavity (%)                                                                                                                    1
State                                                                                                                                  0
Region                                                                                                                                 0
Zone                                                                                                                                   0
dtype: int64

In [33]:

for col in dataset3.columns:
     if col in attribute_categories['family_planning']:
        print("'"+col+"'")

'18. Any method (%)'
'19. Any modern method (%)'
'20. Female sterilization (%)'
'21. Male sterilization (%)'
'22. IUD/PPIUD (%)'
'23. Pill (%)'
'24. Condom (%)'
'25. Total unmet need (%)'
'26. Unmet need for spacing (%)'

In [34]:
dataset3=dataset3.drop(['18. Any method (%)',
'20. Female sterilization (%)',
'21. Male sterilization (%)',
'22. IUD/PPIUD (%)',
'23. Pill (%)',
'24. Condom (%)',
'26. Unmet need for spacing (%)'], axis=1)

In [35]:
for col in dataset3.columns:
     if col in attribute_categories['maternity_care']:
        print("'"+col+"'")
#         print(dataset3[col].corr(dataset3['68. Children under 5 years who are stunted11 (%)']))

'29. Mothers who had antenatal check-up in the first trimester (%)'
'30. Mothers who had at least 4 antenatal care visits (%)'
'31. Mothers whose last birth was protected against neonatal tetanus6 (%)'
'32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)'
'33. Mothers who had full antenatal care7 (%)'
'35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)'
'39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)'

In [36]:
dataset3=dataset3.drop(['29. Mothers who had antenatal check-up in the first trimester (%)',
'31. Mothers whose last birth was protected against neonatal tetanus6 (%)',
'33. Mothers who had full antenatal care7 (%)',
'35. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
'39. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)'], axis=1)

In [37]:
for col in dataset3.columns:
     if col in attribute_categories['delivery_care']:
        print("'"+col+"'")
        #print(dataset3[col].corr(dataset3['68. Children under 5 years who are stunted11 (%)']))

'40. Institutional births (%)'
'41. Institutional births in public facility (%)'
'42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)'
'43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)'
'44. Births delivered by caesarean section (%)'
'46. Births in a public health facility delivered by caesarean section (%)'

In [38]:
dataset3=dataset3.drop(['41. Institutional births in public facility (%)',
'42. Home delivery conducted by skilled health personnel (out of total deliveries) (%)',
'43. Births assisted by a doctor/nurse/LHV/ANM/other health personnel (%)',
'44. Births delivered by caesarean section (%)',
'46. Births in a public health facility delivered by caesarean section (%)'], axis=1)

In [39]:
for col in dataset3.columns:
     if col in attribute_categories['child_immunisation']:
        print("'"+col+"'")
        #print(dataset3[col].corr(dataset3['68. Children under 5 years who are stunted11 (%)']))

'47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)'
'48. Children age 12-23 months who have received BCG (%)'
'49. Children age 12-23 months who have received 3 doses of polio vaccine (%)'
'50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)'
'51. Children age 12-23 months who have received measles vaccine (%)'
'52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)'
'53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)'
'54. Children age 12-23 months who received most of the vaccinations in public health facility (%)'
'55. Children age 12-23 months who received most of the vaccinations in private health facility (%)'

In [40]:
dataset3=dataset3.drop(['48. Children age 12-23 months who have received BCG (%)',
'49. Children age 12-23 months who have received 3 doses of polio vaccine (%)',
'50. Children age 12-23 months who have received 3 doses of DPT vaccine (%)',
'51. Children age 12-23 months who have received measles vaccine (%)',
'52. Children age 12-23 months who have received 3 doses of Hepatitis B vaccine (%)',
'54. Children age 12-23 months who received most of the vaccinations in public health facility (%)',
'55. Children age 12-23 months who received most of the vaccinations in private health facility (%)',
], axis=1)

In [41]:
attribute_categories.keys()

dict_keys(['population', 'literacy', 'marriage', 'family_planning', 'maternity_care', 'delivery_care', 'child_immunisation', 'childhood_diseases', 'child_nutrition', 'adult_nutrition', 'anaemia', 'blood_sugar_level', 'hypertension', 'women_examination'])

In [42]:
for col in dataset3.columns:
     if col in attribute_categories['child_nutrition']:
        print("'"+col+"'")
        #print(dataset3[col].corr(dataset3['68. Children under 5 years who are stunted11 (%)']))

'62. Children under age 3 years breastfed within one hour of birth8 (%)'
'65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)'
'67. Total children age 6-23 months receiving an adequate diet9 10 (%)'
'68. Children under 5 years who are stunted11 (%)'
'69. Children under 5 years who are wasted11 (%)'
'70. Children under 5 years who are severely wasted12 (%)'
'71. Children under 5 years who are underweight11 (%)'

In [43]:
dataset3=dataset3.drop(['69. Children under 5 years who are wasted11 (%)',
'70. Children under 5 years who are severely wasted12 (%)',
'71. Children under 5 years who are underweight11 (%)',
], axis=1)

In [44]:
for col in dataset3.columns:
     if col in attribute_categories['anaemia']:
        print("'"+col+"'")
        print(dataset3[col].corr(dataset3['68. Children under 5 years who are stunted11 (%)']))

'76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)'
0.383067146198733
'77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)'
0.2768658055712757
'79. All women age 15-49 years who are anaemic (%)'
0.28289349304889133
'80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)'
0.3281633867303666

In [45]:
dataset3=dataset3.drop(['77. Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl) (%)'
], axis=1)

In [46]:
len(dataset3.columns)

36

In [47]:
dataset3.corr()['68. Children under 5 years who are stunted11 (%)']

1. Population (female) age 6+ years who ever attended school (%)                                -0.577464
3. Sex ratio of the total population (females per 1000 males)                                    0.008757
4. Sex ratio at birth for children born in the last five years (females per 1000 males)         -0.029723
6. Households with electricity (%)                                                              -0.586164
7. Households with an improved drinking-water source1 (%)                                        0.005558
8. Households using improved sanitation facility2 (%)                                           -0.607010
9. Households using clean fuel for cooking3 (%)                                                 -0.520680
10. Households using iodized salt (%)                                                           -0.112023
11. Households with any usual member covered by a health scheme or health insurance (%)         -0.291284
12. Women who are literate (%)                                                                  -0.650422
13. Men who are literate (%)                                                                    -0.514971
14. Women with 10 or more years of schooling (%)                                                -0.591046
15. Women age 20-24 years married before age 18 years (%)                                        0.538721
17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)     0.268249
19. Any modern method (%)                                                                       -0.269643
25. Total unmet need (%)                                                                         0.214041
30. Mothers who had at least 4 antenatal care visits (%)                                        -0.572111
32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)       -0.490050
40. Institutional births (%)                                                                    -0.455087
47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)   -0.290314
53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)                 -0.299153
62. Children under age 3 years breastfed within one hour of birth8 (%)                          -0.277880
65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)                   -0.369382
67. Total children age 6-23 months receiving an adequate diet9 10 (%)                           -0.412613
68. Children under 5 years who are stunted11 (%)                                                 1.000000
72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                      0.633503
73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                        0.552667
74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)                                    -0.636356
75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)                                      -0.573015
76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)                                    0.383067
79. All women age 15-49 years who are anaemic (%)                                                0.282893
80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)                                         0.328163
Name: 68. Children under 5 years who are stunted11 (%), dtype: float64

In [48]:
#IRRELEVANT

dataset3=dataset3.drop(['3. Sex ratio of the total population (females per 1000 males)',
                        '6. Households with electricity (%)', '11. Households with any usual member covered by a health scheme or health insurance (%)',
                        '17. Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)'
], axis=1)

In [49]:
dataset3.shape

(913, 32)

In [50]:
dataset3.isna().sum().sum()

1315

In [51]:
1315/(913*32)

0.04500958378970427

In [52]:
dataset3.isna().sum()

District                                                                                           0
1. Population (female) age 6+ years who ever attended school (%)                                   0
4. Sex ratio at birth for children born in the last five years (females per 1000 males)           77
7. Households with an improved drinking-water source1 (%)                                          1
8. Households using improved sanitation facility2 (%)                                              1
9. Households using clean fuel for cooking3 (%)                                                    1
10. Households using iodized salt (%)                                                              1
12. Women who are literate (%)                                                                     1
13. Men who are literate (%)                                                                      65
14. Women with 10 or more years of schooling (%)                                                   1
15. Women age 20-24 years married before age 18 years (%)                                         63
19. Any modern method (%)                                                                          4
25. Total unmet need (%)                                                                           4
30. Mothers who had at least 4 antenatal care visits (%)                                          39
32. Mothers who consumed iron folic acid for 100 days or more when they were pregnant (%)         39
40. Institutional births (%)                                                                      28
47. Children age 12-23 months fully immunized (BCG measles and 3 doses each of polio/DPT) (%)    242
53. Children age 9-59 months who received a vitamin A dose in last 6 months (%)                   41
62. Children under age 3 years breastfed within one hour of birth8 (%)                            70
65. Breastfeeding children age 6-23 months receiving an adequate diet9 10 (%)                    209
67. Total children age 6-23 months receiving an adequate diet9 10 (%)                            136
68. Children under 5 years who are stunted11 (%)                                                  37
72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                        2
73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%)                         69
74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%)                                       2
75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%)                                        69
76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%)                                     41
79. All women age 15-49 years who are anaemic (%)                                                  2
80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%)                                          70
State                                                                                              0
Region                                                                                             0
Zone                                                                                               0
dtype: int64

In [53]:
dataset3=dataset3.dropna(axis=0,how='any',inplace=False)
dataset3

,District,1. Population (female) age 6+ years who ever attended school (%),4. Sex ratio at birth for children born in the last five years (females per 1000 males),7. Households with an improved drinking-water source1 (%),8. Households using improved sanitation facility2 (%),9. Households using clean fuel for cooking3 (%),10. Households using iodized salt (%),12. Women who are literate (%),13. Men who are literate (%),14. Women with 10 or more years of schooling (%),...,72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%),75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%),76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%),79. All women age 15-49 years who are anaemic (%),80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%),State,Region,Zone
0,Srikakulam,54.3,865.0,74.7,26.6,31.6,77.3,55.7,76.2,31.2,...,22.7,18.8,21.0,12.4,73.0,71.8,28.3,AP,Rural,Southern Zone
2,Vizianagaram,51.6,917.0,92.5,18.6,34.8,63.3,49.3,63.6,28.4,...,29.7,25.5,16.0,28.0,80.9,77.1,45.4,AP,Rural,Southern Zone
7,East Godavari,64.1,968.0,82.1,50.1,37.3,77.1,66.8,78.1,28.2,...,18.2,15.2,32.2,24.7,65.7,69.1,47.6,AP,Rural,Southern Zone
9,West Godavari,68.7,755.0,73.4,55.6,54.2,83.0,68.0,63.1,34.7,...,16.3,16.6,36.9,39.5,55.5,61.5,18.6,AP,Rural,Southern Zone
17,Prakasam,49.8,768.0,59.5,49.6,62.0,74.3,52.1,68.2,25.5,...,17.9,12.7,29.3,34.8,57.8,59.4,28.5,AP,Rural,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,Haora,79.6,901.0,99.7,56.6,27.3,94.9,76.2,84.0,27.7,...,19.7,16.3,20.6,11.6,46.2,59.8,32.6,WB,Rural,Eastern Zone
1541,Kolkata,82.5,1020.0,96.2,50.2,69.6,98.5,80.8,84.3,49.6,...,7.3,17.2,40.7,42.8,70.2,46.4,24.6,WB,Urban,Eastern Zone
1543,South Twenty Four Parganas,74.4,1068.0,98.5,50.1,10.3,94.1,72.9,73.9,18.0,...,20.3,20.6,18.5,9.2,65.7,67.7,32.0,WB,Rural,Eastern Zone
1545,Paschim Medinipur,73.4,868.0,96.8,39.3,9.3,91.3,69.2,82.4,22.6,...,29.9,25.5,14.7,15.3,53.7,67.2,37.1,WB,Rural,Eastern Zone
1547,Purba Medinipur,77.9,1053.0,99.1,66.7,6.6,85.7,75.2,90.4,27.0,...,20.2,6.5,19.0,18.3,46.2,59.4,27.5,WB,Rural,Eastern Zone

In [54]:
dataset3.isna().sum().sum()

0

In [55]:
dataset3.to_csv('./../Data/working_data/cleaned_data_3.csv',index=False)

## DATA PREPROCESSING: Z-Score Normalisation/Standardisation

In [56]:
to_ignore = ['District', 'State', 'Region', 'Zone']
for col in dataset3.columns:
    if col not in to_ignore:
        dataset3[col]=(dataset3[col] - dataset3[col].mean())/dataset3[col].std()

In [57]:
dataset3

,District,1. Population (female) age 6+ years who ever attended school (%),4. Sex ratio at birth for children born in the last five years (females per 1000 males),7. Households with an improved drinking-water source1 (%),8. Households using improved sanitation facility2 (%),9. Households using clean fuel for cooking3 (%),10. Households using iodized salt (%),12. Women who are literate (%),13. Men who are literate (%),14. Women with 10 or more years of schooling (%),...,72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%),75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%),76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%),79. All women age 15-49 years who are anaemic (%),80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%),State,Region,Zone
0,Srikakulam,-1.027700,-0.528802,-0.915598,-0.705917,0.001458,-2.394772,-0.634679,-0.798898,0.009967,...,-0.067378,-0.184924,0.453209,-0.311178,1.011736,1.588169,0.473650,AP,Rural,Southern Zone
2,Vizianagaram,-1.253004,-0.112195,0.352274,-1.028720,0.116194,-4.390536,-1.039567,-2.112033,-0.172335,...,0.658967,0.524099,-0.079725,1.429084,1.495927,1.995139,2.099764,AP,Rural,Southern Zone
7,East Godavari,-0.209930,0.296399,-0.388505,0.242319,0.205831,-2.423283,0.067550,-0.600886,-0.185356,...,-0.534314,-0.565892,1.646980,1.060952,0.564318,1.380844,2.308971,AP,Rural,Southern Zone
9,West Godavari,0.173921,-1.410085,-1.008195,0.464246,0.811781,-1.582211,0.143467,-2.164141,0.237845,...,-0.731465,-0.417738,2.147937,2.711969,-0.060841,0.797264,-0.448765,AP,Rural,Southern Zone
17,Prakasam,-1.403207,-1.305933,-1.998276,0.222143,1.091450,-2.822436,-0.862428,-1.632635,-0.361147,...,-0.565443,-0.830452,1.337878,2.187660,0.080126,0.636011,0.492669,AP,Rural,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,Haora,1.083481,-0.240382,0.865121,0.504597,-0.152719,0.114187,0.662230,0.013994,-0.217910,...,-0.378669,-0.449485,0.410574,-0.400422,-0.630839,0.666726,0.882556,WB,Rural,Eastern Zone
1541,Kolkata,1.325475,0.713006,0.615821,0.246354,1.363948,0.627384,0.953244,0.045260,1.207951,...,-1.665337,-0.354243,2.552967,3.080102,0.840123,-0.362218,0.121801,WB,Urban,Eastern Zone
1543,South Twenty Four Parganas,0.649563,1.097566,0.779647,0.242319,-0.762254,0.000144,0.453460,-1.038598,-0.849456,...,-0.316411,0.005560,0.186742,-0.668155,0.564318,1.273342,0.825499,WB,Rural,Eastern Zone
1545,Paschim Medinipur,0.566117,-0.504767,0.658558,-0.193466,-0.798109,-0.399009,0.219383,-0.152753,-0.549960,...,0.679719,0.524099,-0.218288,0.012332,-0.171163,1.234949,1.310480,WB,Rural,Eastern Zone
1547,Purba Medinipur,0.941623,0.977391,0.822384,0.912136,-0.894917,-1.197314,0.598966,0.680983,-0.263485,...,-0.326787,-1.486563,0.240035,0.346998,-0.630839,0.636011,0.397574,WB,Rural,Eastern Zone

In [58]:
len(dataset3.columns)

32

In [59]:
dataset3.to_csv('./../Data/working_data/normalised_data_4.csv')

## DATA PREPROCESSING: Unsupervised Discretisation : Equal Interval Binning

In [60]:
dataset4=dataset3.copy()
to_ignore = ['District', 'State', 'Region', 'Zone']
for col in dataset4.columns:
    if col not in to_ignore:
        dataset4[col]=pd.cut(dataset4[col],3,labels=['low', 'medium', 'high'])

In [61]:
dataset4

,District,1. Population (female) age 6+ years who ever attended school (%),4. Sex ratio at birth for children born in the last five years (females per 1000 males),7. Households with an improved drinking-water source1 (%),8. Households using improved sanitation facility2 (%),9. Households using clean fuel for cooking3 (%),10. Households using iodized salt (%),12. Women who are literate (%),13. Men who are literate (%),14. Women with 10 or more years of schooling (%),...,72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%),75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%),76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%),79. All women age 15-49 years who are anaemic (%),80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%),State,Region,Zone
0,Srikakulam,medium,low,medium,low,low,medium,medium,medium,medium,...,medium,medium,medium,low,high,high,medium,AP,Rural,Southern Zone
2,Vizianagaram,low,low,high,low,medium,low,medium,low,low,...,medium,medium,low,medium,high,high,high,AP,Rural,Southern Zone
7,East Godavari,medium,medium,high,medium,medium,medium,medium,medium,low,...,low,low,medium,medium,high,high,high,AP,Rural,Southern Zone
9,West Godavari,medium,low,medium,medium,medium,medium,medium,low,medium,...,low,low,high,high,medium,high,low,AP,Rural,Southern Zone
17,Prakasam,low,low,medium,medium,medium,medium,medium,medium,low,...,low,low,medium,medium,medium,high,medium,AP,Rural,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,Haora,high,low,high,medium,low,high,high,high,low,...,medium,low,medium,low,medium,high,medium,WB,Rural,Eastern Zone
1541,Kolkata,high,medium,high,medium,high,high,high,high,medium,...,low,medium,high,high,high,medium,medium,WB,Urban,Eastern Zone
1543,South Twenty Four Parganas,medium,medium,high,medium,low,high,medium,medium,low,...,medium,medium,medium,low,high,high,medium,WB,Rural,Eastern Zone
1545,Paschim Medinipur,medium,low,high,medium,low,high,medium,high,low,...,medium,medium,low,low,medium,high,medium,WB,Rural,Eastern Zone
1547,Purba Medinipur,high,medium,high,medium,low,medium,high,high,low,...,medium,low,medium,medium,medium,high,medium,WB,Rural,Eastern Zone

In [62]:
dataset4.to_csv('./../Data/working_data/equal_interval_discretised_data_5.csv')

## DATA PREPROCESSING: Unsupervised Discretisation : Equal Frequency Binning

In [63]:
dataset5=dataset3.copy()
to_ignore = ['District', 'Households surveyed', 'Women age 15-49 years interviewed',
       'Men age 15-49 years interviewed', 'State', 'Region', 'Zone']
for col in dataset5.columns:
    if col not in to_ignore:
        dataset5[col]=pd.qcut(dataset5[col],3,labels=['low', 'medium', 'high'])

In [64]:
dataset5

,District,1. Population (female) age 6+ years who ever attended school (%),4. Sex ratio at birth for children born in the last five years (females per 1000 males),7. Households with an improved drinking-water source1 (%),8. Households using improved sanitation facility2 (%),9. Households using clean fuel for cooking3 (%),10. Households using iodized salt (%),12. Women who are literate (%),13. Men who are literate (%),14. Women with 10 or more years of schooling (%),...,72. Women whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),73. Men whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2) (%),74. Women who are overweight or obese (BMI >=25.0 kg/m2) (%),75. Men who are overweight or obese (BMI >=25.0 kg/m2) (%),76. Children age 6-59 months who are anaemic (<11.0 g/dl) (%),79. All women age 15-49 years who are anaemic (%),80. Men age 15-49 years who are anaemic (<13.0 g/dl) (%),State,Region,Zone
0,Srikakulam,low,low,low,low,medium,low,low,low,medium,...,medium,medium,high,medium,high,high,high,AP,Rural,Southern Zone
2,Vizianagaram,low,medium,medium,low,high,low,low,low,medium,...,high,high,medium,high,high,high,high,AP,Rural,Southern Zone
7,East Godavari,medium,medium,low,medium,high,low,medium,low,medium,...,medium,low,high,high,medium,high,high,AP,Rural,Southern Zone
9,West Godavari,medium,low,low,medium,high,low,medium,low,medium,...,low,medium,high,high,medium,high,medium,AP,Rural,Southern Zone
17,Prakasam,low,low,low,medium,high,low,low,low,medium,...,low,low,high,high,medium,high,high,AP,Rural,Southern Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,Haora,high,medium,high,medium,medium,medium,high,medium,medium,...,medium,medium,high,medium,low,high,high,WB,Rural,Eastern Zone
1541,Kolkata,high,high,medium,medium,high,high,high,medium,high,...,low,medium,high,high,high,medium,medium,WB,Urban,Eastern Zone
1543,South Twenty Four Parganas,high,high,high,medium,low,low,medium,low,low,...,medium,medium,medium,low,medium,high,high,WB,Rural,Eastern Zone
1545,Paschim Medinipur,high,low,high,medium,low,low,medium,medium,medium,...,high,high,medium,medium,medium,high,high,WB,Rural,Eastern Zone
1547,Purba Medinipur,high,high,high,high,low,low,high,high,medium,...,medium,low,medium,high,low,high,high,WB,Rural,Eastern Zone

In [65]:
dataset5.to_csv('./../Data/working_data/equal_frequency_discretised_data_6.csv')